SET ECHO ON
SET TAB OFF
SET SERVEROUTPUT ON

REM 조사 CASE 표현식으로 변경 (Searched CASE expression)
DECLARE
v_BOOL  BOOLEAN := TRUE;
v_TRUE BOOLEAN := TRUE;
v_FALSE BOOLEAN := FALSE;
v_STR STRING(100);
BEGIN
v_STR := CASE V_BOOL WHEN TRUE THEN 'v_BOOL is TRUE' -- TRUE
WHEN v_TRUE  THEN 'v_TRUE' -- TRUE
WHEN FALSE THEN 'v_BOOL =FALSE' -- FALSE
WHEN v_FALSE THEN 'v_BOOL = v_FALSE' -- FALSE
ELSE 'v_BOOL IS NULL'
END;
dbms_output.put_line(v_STR);
END;
/
